### ISSUE TITLE
RescueSDK - CD/CI(Jenkins) build issue from version 5.5 and above

### ISSUE THREAD

**Issue by sureshpeddisetti** [LogmeinRescue/iOS-SDK#49]
**Environment**
Xcode - 11.2.1
Cocoapods - 1.9.3

**Description**
We are using RescueSDK for one of the app and we are using a CD/CI system, where a build server is configured that runs XCode to process the builds, but the build process is getting struck while **Preparing Artifacts** for RescueSDK version 5.5 and above.

Note - While committing the code to the repo, we won't commit **pods**, we will just commit the **podfile** and **podfile.lock**, so our CD/CI system is responsible to generate **pods**.

As mentioned in this post [Xcodebuild hangs on '[CP] Prepare Artifacts'](https://sugeul.github.io/2020-06-02-xcodebuild-hang-on-CP-Prepare-artifacts/) we went to CD/CI system and changed **cat > $ARTIFACT_LIST_FILE** to **touch > $ARTIFACT_LIST_FILE** in **Pods-{TARGET}-artifacts.sh**, then build succeeded. But this is not possible for us to change every time when there is a new push to the branch because our CD/CI system clears the data once the build succeeded. Is there anything that we are missing here ? Please suggest.

Thanks.

<img width="539" alt="Screenshot 2020-07-03 at 12 19 09 PM" src="https://user-images.githubusercontent.com/35369222/86440129-8a4e8f80-bd27-11ea-884e-7b9612089e46.png">

**Comment by exceptioncatcher91** [comment]
Hi @sureshpeddisetti,

This is a Cocoapod issue. They have already known about that: https://github.com/CocoaPods/CocoaPods/issues/9817
The new Cocoapod version (1.10) will contain the fix. If you do not want to wait for it, you can create your own build from the master branch of Cocoapods, which already has this fix. There is a third way to solve this problem: You should put your temporary solution (replace cat to touch) into your build script before you call the ‘xcodebuild’ command so that it would fix the issue every time your build runs.

Regards, Daniel

**Comment by exceptioncatcher91** [comment]
Hi @sureshpeddisetti,

FYI: Cocoapods 1.10 beta is released: https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.1

Regards, Daniel
